# Generated by Django 3.0.10 on 2024-07-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portofolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_model',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='projects/files/'),
        ),
    ]
