# Generated by Django 3.0.10 on 2024-07-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portofolio', '0002_auto_20240719_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_model',
            name='phone',
        ),
    ]
