# Generated by Django 3.0.10 on 2024-07-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portofolio', '0003_remove_contact_model_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_model',
            name='file',
            field=models.FileField(default='path/to/default/file', upload_to='projects/'),
        ),
    ]
