# Generated by Django 3.0.10 on 2024-07-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portofolio', '0004_auto_20240720_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_model',
            name='file',
            field=models.FileField(upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project_model',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
