# Generated by Django 3.0.10 on 2024-07-21 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_portofolio', '0005_auto_20240720_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project_model',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project_model',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
